var express = require('express');
var router = express.Router();

const glossaryList = [
  {'ID' : '1', 'Term':'Agile software development' , 'Definition': 'It is an approach of software development process which focuses on delivery over documentation. It allows continuous delivery of valuable work which is completed in iterations where the development team constantly receives feedback from the client.', 'Reference': 'https://www.techtarget.com/searchsoftwarequality/definition/agile-software-development'},
  {'ID' : '2', 'Term':'Cloud computing' , 'Definition': 'It refers to the delivery of computer resources such as servers, storage, databases, analytics, etc over the internet which are hosted on cloud networks.', 'Reference': '2. https://azure.microsoft.com/en-au/resources/cloud-computing-dictionary/what-is-cloud-computing#:~:text=Simply%20put%2C%20cloud%20computing%20is,resources%2C%20and%20economies%20of%20scale.'},
  {'ID' : '3', 'Term':'Kubernetes' , 'Definition': 'Kubernetes allows automation for container deployment, management and scaling of containerised applications. It follows a master-node architecture which involves a main node and worker nodes, if a node fails the node is restarted and it resolves the issue. ', 'Reference': 'https://kubernetes.io'},
  {'ID' : '4', 'Term':'Containers' , 'Definition': 'Containers a tool that allows packaging of software program and their dependencies into one package, these packages can be run on the desired platform. These containers are light-weight and secure. ', 'Reference': 'https://www.docker.com/resources/what-container/'},
  {'ID' : '5', 'Term':'Continuous Integration(CI)' , 'Definition': 'It refers to the practice of pushing changed code into a shared repository frequently, building and testing it for frequent delivery of applications. the CI system provides an instant feedback on the same.', 'Reference': 'https://about.gitlab.com/topics/ci-cd/cloud-native-continuous-integration/#:~:text=CI%20is%20the%20practice%20of,repository%20as%20their%20source%20code.'},
  {'ID' : '6', 'Term':'Continuous Delivery(CD)' , 'Definition': 'It is a software development practice that automates the process of testing and pushes the code changes to a production like environment. It ensures that software is ready for deployment and can be deployed through a click of a button.', 'Reference': 'https://www.atlassian.com/continuous-delivery/principles/continuous-integration-vs-delivery-vs-deployment'},
  {'ID' : '7', 'Term':'Micro-Services' , 'Definition': 'It refers to an architectural approach of software development, in this approach software services are divided based on functionalities and they are integrated to work as a whole. If there is a bug in one service it wont take down the whole system.', 'Reference': '7. https://www.bmc.com/blogs/devops-microservices/'},
  {'ID' : '8', 'Term':'Continuous Testing' , 'Definition': 'It refers to the process of automated testing of code overtime a change is made. These tests are carried out at regular interval throughout the development process.', 'Reference': 'https://www.globalapptesting.com/blog/what-is-continuous-testing#:~:text=Continuous%20testing%20in%20DevOps,-Continuous%20testing%20was&text=The%20main%20goal%20being%20to,time%20code%20changes%20are%20made.'},
  {'ID' : '9', 'Term':'Deployment' , 'Definition': 'It refers to the process of building and packaging the application code and packages, these go through a series of steps and is then released on the required platform for the end-user.', 'Reference': '9. https://octopus.com/devops/continuous-delivery/deployments-vs-releases/#:~:text=However%2C%20modern%20software%20delivery%20practices,software%20available%20to%20a%20user'},
  {'ID' : '10', 'Term':'DevOps' , 'Definition': 'It is the combination of software development and operations, where these two teams work together for faster delivery of software and for better communication and collaboration.', 'Reference': 'https://about.gitlab.com/topics/devops/'},
  {'ID' : '11', 'Term': 'Infrastructure as Code (IaC)', 'Definition': 'It refers to the management and provisioning of infrastructure such as networks, virtual machines and load balancers through code instead of using a manual process.', 'Reference': 'https://learn.microsoft.com/en-us/devops/deliver/what-is-infrastructure-as-code'},
  {'ID' : '12', 'Term': 'Cloud Orchestration', 'Definition': 'It refers to the process of automating the coordination and management of apps, workloads, virtual machines and infrastructure in public and private cloud platforms. It helps reduce repetitive work of managing the resources.', 'Reference': 'https://www.cisco.com/c/en/us/solutions/cloud/what-is-cloud-orchestration.html'},
  {'ID' : '13', 'Term': 'Version Control', 'Definition': 'They are systems which store and keep track of changes made to the code, they provide a structure and logical means to organise files. They are a useful tool especially when working in teams.', 'Reference': 'https://cloud.google.com/architecture/devops/devops-tech-version-control#:~:text=A%20version%20control%20system%20records,groups%20called%20commits%20or%20revisions.'},
  {'ID' : '14', 'Term': 'Incident Management', 'Definition': 'Management of unplanned events (Complete outage, reduced performance, bugs) and interruptions by DevOps and the IT team. The aim is to provide efficient and reliable service.', 'Reference': 'https://pagertree.com/learn/incident-management/what-is-incident-management-beginners-guide#:~:text=Incident%20management%20is%20the%20process,possible%20while%20minimizing%20business%20impact.'},
  {'ID' : '15', 'Term': 'Scalability', 'Definition': 'Scalability in DevOps refers to the ability of a system to handle increased workload and the ability to scale down as the demand reduces this is done by either using additional resources or by optimising them.', 'Reference': 'https://reviewnprep.com/blog/efficient-methods-for-scaling-devops-approaches-to-overcome-challenges/#:~:text=Scalability%20refers%20to%20the%20ability,DevOps%2C%20thanks%20to%20specific%20techniques.'},
  {'ID' : '16', 'Term': 'Automation', 'Definition': 'It is the process of reducing human assistance in tasks with the use of technology to perform those tasks, tools and scripts are used to replace redundant work.', 'Reference': 'https://www.redhat.com/en/topics/automation/what-is-devops-automation#:~:text=DevOps%20automation%20is%20the%20addition,faster%20to%20applications%20in%20production.'},
  {'ID' : '17', 'Term': 'SLIs(Service Level Indicators)', 'Definition': 'It is the metric used to quantitatively measure the performance of the service. Some of the metrics used includes latency, availability, error rate and durability.', 'Reference': 'https://sematext.com/glossary/service-level-indicator/#:~:text=Service%20Level%20Indicators%20(SLIs)&text=SLIs%20can%20measure%20various%20aspects,page%20or%20processing%20a%20transaction.'},
  {'ID' : '18', 'Term': 'Immutable infrastructure', 'Definition': 'It is a concept, immutable means once a component (like server) is deployed its configuration cannot be altered, instead new infrastructure and components are created to replace them.', 'Reference': 'https://www.professional-devops.com/immutable-infrastructure.html#:~:text=Immutable%20infrastructure%20means%20servers%20that,to%20keep%20the%20server%20intact.'},
  {'ID' : '19', 'Term': 'Terraform', 'Definition': 'It is a tool that facilitates infrastructure as code, using this teams can provide all components of infrastructure as code this code lies in a configuration file.', 'Reference': 'https://www.techtarget.com/searchitoperations/definition/Terraform#:~:text=HashiCorp%20Terraform%20is%20an%20infrastructure,on%2Dpremises%20and%20cloud%20environments.'},
  {'ID' : '20', 'Term': 'Devops Metrics', 'Definition': 'It is the industry standard for quantitative measurement of reliability and quality of software delivery within the organisation. Some of the metrics included are deployment frequency, lead time to changes, time to restore service, deployment time, etc.', 'Reference': 'https://www.pluralsight.com/blog/teams/devops-metrics#:~:text=DevOps%20metrics%20are%20regarded%20as,causing%20failures%20in%20deployed%20code.'},

];

/* GET home page. */
router.get('/', function(req, res, next) {
  res.render('index', { title: 'DevOps Glossary', Glossary: glossaryList });
});

module.exports = router;
