var express = require('express');
var router = express.Router();

const glossaryList = [
  {'ID' : '1', 'Term':'Agile software development' , 'Definition': 'It is an approach of software development process which focuses on delivery over documentation. It allows continuous delivery of valuable work which is completed in iterations where the development team constantly receives feedback from the client.', 'Reference': 'https://www.techtarget.com/searchsoftwarequality/definition/agile-software-development'},
  {'ID' : '2', 'Term':'Cloud computing' , 'Definition': 'It refers to the delivery of computer resources such as servers, storage, databases, analytics, etc over the internet which are hosted on cloud networks.', 'Reference': '2. https://azure.microsoft.com/en-au/resources/cloud-computing-dictionary/what-is-cloud-computing#:~:text=Simply%20put%2C%20cloud%20computing%20is,resources%2C%20and%20economies%20of%20scale.'},
  {'ID' : '3', 'Term':'Kubernetes' , 'Definition': 'Kubernetes allows automation for container deployment, management and scaling of containerised applications. It follows a master-node architecture which involves a main node and worker nodes, if a node fails the node is restarted and it resolves the issue. ', 'Reference': 'https://kubernetes.io'},
  {'ID' : '4', 'Term':'Containers' , 'Definition': 'Containers a tool that allows packaging of software program and their dependencies into one package, these packages can be run on the desired platform. These containers are light-weight and secure. ', 'Reference': 'https://www.docker.com/resources/what-container/'},
  {'ID' : '5', 'Term':'Continuous Integration(CI)' , 'Definition': 'It refers to the practice of pushing changed code into a shared repository frequently, building and testing it for frequent delivery of applications. the CI system provides an instant feedback on the same.', 'Reference': 'https://about.gitlab.com/topics/ci-cd/cloud-native-continuous-integration/#:~:text=CI%20is%20the%20practice%20of,repository%20as%20their%20source%20code.'},
  {'ID' : '6', 'Term':'Continuous Delivery(CD)' , 'Definition': 'It is a software development practice that automates the process of testing and pushes the code changes to a production like environment. It ensures that software is ready for deployment and can be deployed through a click of a button.', 'Reference': 'https://www.atlassian.com/continuous-delivery/principles/continuous-integration-vs-delivery-vs-deployment'},
  {'ID' : '7', 'Term':'Micro-Services' , 'Definition': 'It refers to an architectural approach of software development, in this approach software services are divided based on functionalities and they are integrated to work as a whole. If there is a bug in one service it wont take down the whole system.', 'Reference': '7. https://www.bmc.com/blogs/devops-microservices/'},
  {'ID' : '8', 'Term':'Continuous Testing' , 'Definition': 'It refers to the process of automated testing of code overtime a change is made. These tests are carried out at regular interval throughout the development process.', 'Reference': 'https://www.globalapptesting.com/blog/what-is-continuous-testing#:~:text=Continuous%20testing%20in%20DevOps,-Continuous%20testing%20was&text=The%20main%20goal%20being%20to,time%20code%20changes%20are%20made.'},
  {'ID' : '9', 'Term':'Deployment' , 'Definition': 'It refers to the process of building and packaging the application code and packages, these go through a series of steps and is then released on the required platform for the end-user.', 'Reference': '9. https://octopus.com/devops/continuous-delivery/deployments-vs-releases/#:~:text=However%2C%20modern%20software%20delivery%20practices,software%20available%20to%20a%20user'},
  {'ID' : '10', 'Term':'DevOps' , 'Definition': 'It is the combination of software development and operations, where these two teams work together for faster delivery of software and for better communication and collaboration.', 'Reference': 'https://about.gitlab.com/topics/devops/'},
  {'ID' : '11', 'Term': 'Infrastructure as Code (IaC)', 'Definition': 'It refers to the management and provisioning of infrastructure such as networks, virtual machines and load balancers through code instead of using a manual process.', 'Reference': 'https://learn.microsoft.com/en-us/devops/deliver/what-is-infrastructure-as-code'},
  {'ID' : '12', 'Term': 'Cloud Orchestration', 'Definition': 'It refers to the process of automating the coordination and management of apps, workloads, virtual machines and infrastructure in public and private cloud platforms. It helps reduce repetitive work of managing the resources.', 'Reference': 'https://www.cisco.com/c/en/us/solutions/cloud/what-is-cloud-orchestration.html'},
  {'ID' : '13', 'Term': 'Version Control', 'Definition': 'They are systems which store and keep track of changes made to the code, they provide a structure and logical means to organise files. They are a useful tool especially when working in teams.', 'Reference': 'https://cloud.google.com/architecture/devops/devops-tech-version-control#:~:text=A%20version%20control%20system%20records,groups%20called%20commits%20or%20revisions.'},
  {'ID' : '14', 'Term': 'Incident Management', 'Definition': 'Management of unplanned events (Complete outage, reduced performance, bugs) and interruptions by DevOps and the IT team. The aim is to provide efficient and reliable service.', 'Reference': 'https://pagertree.com/learn/incident-management/what-is-incident-management-beginners-guide#:~:text=Incident%20management%20is%20the%20process,possible%20while%20minimizing%20business%20impact.'},
  {'ID' : '15', 'Term': 'Scalability', 'Definition': 'Scalability in DevOps refers to the ability of a system to handle increased workload and the ability to scale down as the demand reduces this is done by either using additional resources or by optimising them.', 'Reference': 'https://reviewnprep.com/blog/efficient-methods-for-scaling-devops-approaches-to-overcome-challenges/#:~:text=Scalability%20refers%20to%20the%20ability,DevOps%2C%20thanks%20to%20specific%20techniques.'},
  {'ID' : '16', 'Term': 'Automation', 'Definition': 'It is the process of reducing human assistance in tasks with the use of technology to perform those tasks, tools and scripts are used to replace redundant work.', 'Reference': 'https://www.redhat.com/en/topics/automation/what-is-devops-automation#:~:text=DevOps%20automation%20is%20the%20addition,faster%20to%20applications%20in%20production.'},
  {'ID' : '17', 'Term': 'SLIs(Service Level Indicators)', 'Definition': 'It is the metric used to quantitatively measure the performance of the service. Some of the metrics used includes latency, availability, error rate and durability.', 'Reference': 'https://sematext.com/glossary/service-level-indicator/#:~:text=Service%20Level%20Indicators%20(SLIs)&text=SLIs%20can%20measure%20various%20aspects,page%20or%20processing%20a%20transaction.'},
  {'ID' : '18', 'Term': 'Immutable infrastructure', 'Definition': 'It is a concept, immutable means once a component (like server) is deployed its configuration cannot be altered, instead new infrastructure and components are created to replace them.', 'Reference': 'https://www.professional-devops.com/immutable-infrastructure.html#:~:text=Immutable%20infrastructure%20means%20servers%20that,to%20keep%20the%20server%20intact.'},
  {'ID' : '19', 'Term': 'Terraform', 'Definition': 'It is a tool that facilitates infrastructure as code, using this teams can provide all components of infrastructure as code this code lies in a configuration file.', 'Reference': 'https://www.techtarget.com/searchitoperations/definition/Terraform#:~:text=HashiCorp%20Terraform%20is%20an%20infrastructure,on%2Dpremises%20and%20cloud%20environments.'},
  {'ID' : '20', 'Term': 'Devops Metrics', 'Definition': 'It is the industry standard for quantitative measurement of reliability and quality of software delivery within the organisation. Some of the metrics included are deployment frequency, lead time to changes, time to restore service, deployment time, etc.', 'Reference': 'https://www.pluralsight.com/blog/teams/devops-metrics#:~:text=DevOps%20metrics%20are%20regarded%20as,causing%20failures%20in%20deployed%20code.'},
  {'ID' : '21', 'Term' : 'Blue/Green Deployments', 'Definition' : 'A deployment strategy where two production environments are used, they swap roles between live and staging with new releases. Lets say the current version of the application is deployed on Blue server so the green server will be used for staging and testing before traffic is directed to it.', 'Reference' : '21. https://octopus.com/devops/glossary/'},
  {'ID' : '22', 'Term' : 'Build server', 'Definition' : 'It is a tool for automation of CI/CD, they automate code compilation from the repository, they run automated tests for code validation and they create deployable packages.', 'Reference' : '21. https://octopus.com/devops/glossary/'},
  {'ID' : '23', 'Term' : 'Chaos Engineering', 'Definition' : 'It is a method of DevOps where failures are accepted. Netflix created a tool called Chaos Monkey that can cause failures randomly through with vulnerabilities can be detected, this method helps in building resilient code.', 'Reference' : '21. https://octopus.com/devops/glossary/'},
  {'ID' : '24', 'Term' : 'Code promotion', 'Definition' : 'Changes made to source code are promoted using a process known as "code promotion." Source code changes are moved from the development branch to the testing or production branch once they have been reviewed and confirmed to be acceptable.', 'Reference' : '24. https://medium.com/@niitwork0921/code-promotion-vs-artifact-promotion-which-one-should-you-use-474500c5b341#:~:text=The%20term%20“code%20promotion”%20is,the%20testing%20or%20production%20branch.'},
  {'ID' : '25', 'Term' : 'Configuration as Code', 'Definition' : 'It is a way of managing components, resources, environments and packages using code instead of doing it manually. The software is pushed to a version control repository and managed through the code.', 'Reference' : 'https://www.browserstack.com/guide/configuration-as-code'},
  {'ID' : '26', 'Term' : 'Cloud Governance', 'Definition' : 'It refers to the policies and procedures for defining, Implementing and overseeing an organisations cloud based operations. These policies and procedures ensure consistency in cloud services and systems.', 'Reference' : '26. https://www.redhat.com/en/topics/automation/what-is-cloud-governance#:~:text=Cloud%20governance%20is%20the%20process,of%20cloud%20services%20and%20systems.'},
  {'ID' : '27', 'Term' : 'Dynamic Infrastructure', 'Definition' : 'It refers to the the Data centre resources such as computer, networking and storage which can automatically provision resources based on demand, increase allocation when the workload increases and decrease when it decreases.', 'Reference' : '27. https://www.techtarget.com/searchcloudcomputing/definition/dynamic-infrastructure#:~:text=Dynamic%20infrastructure%20refers%20to%20a,to%20manage%20these%20resources%20manually.'},
  {'ID' : '28', 'Term' : 'Branching in DevOps', 'Definition' : 'It is the process ion creating separate branches for different features on which developers work. Once the work on a feature is finished that branch is tested upon which it is pushed to the main branch.', 'Reference' : '28. https://www.heptabit.at/blog/devops/devops-branching-strategy-what-is-it-how-it-works#:~:text=Branching%20is%20the%20process%20of,be%20complicated%20and%20get%20messy.'},
  {'ID' : '29', 'Term' : 'Jenkins', 'Definition' : 'It is an open source automation server which allows automation in building, testing and deployment to facilitate CI/CD.', 'Reference' : '29. https://www.techtarget.com/searchsoftwarequality/definition/Jenkins#:~:text=Jenkins%20is%20an%20open%20source,%2FCD%20workflows%2C%20called%20pipelines.'},
  {'ID' : '30', 'Term' : 'Log Aggregation', 'Definition' : 'Log Aggregation involves consolidation of log data from various IT sources such as microservices into a single platform where analysis and review can be performed.', 'Reference' : 'https://www.sumologic.com/glossary/log-aggregation/#:~:text=Log%20aggregation%20is%20a%20software,can%20be%20reviewed%20and%20analyzed.'},
  {'ID' : '31', "Term" : 'CI/CD pipelines', "Definition" : 'It refers to the process of automating software deployment through a path of building, testing, and deployment of code. The goal is to reduce human errors and consistency.', "Reference": 'https://www.redhat.com/en/topics/devops/what-cicd-pipeline'},
  {'ID' : '32', "Term" : 'Release management', "Definition" : 'It refers to the process of managing software version releases with bug fixes, features and enhancements through planning, coordinating and deploying software.', "Reference": ' https://www.splunk.com/en_us/blog/learn/devops-release-management.html#:~:text=In%20a%20DevOps%20environment%2C%20release,%2C%20efficient%2C%20and%20timely%20manner.'},
  {'ID' : '33', "Term" : 'Infrastructure as a Service(IaaS)', "Definition" : 'It is a cloud computing service which offers resources such as compute, storage and networking resources on-demand where users can pay as they go. It helps reduce maintenance and hardware costs.', "Reference": 'https://azure.microsoft.com/en-au/resources/cloud-computing-dictionary/what-is-iaas'},
  {'ID' : '34', "Term" : 'Platform as a Service(PaaS)', "Definition" : ' it provides a cloud based environment for complete development and deployment. It provides support for the complete software development lifecycle, it includes infrastructure, container orchestration and development tools.', "Reference": ' https://azure.microsoft.com/en-au/resources/cloud-computing-dictionary/what-is-paas'},
  {'ID' : '35', "Term" : 'GitOps', "Definition" : 'It is a framework which builds on DevOps practices, used for deploying applications and provides functionality such as version control, collaboration, compliance and CI/CD to automate infrastructure automation.', "Reference": '35. https://about.gitlab.com/topics/gitops/#:~:text=GitOps%20is%20an%20operational%20framework,applies%20them%20to%20infrastructure%20automation.'},
  {'ID' : '36', "Term" : 'Container Orchestration', "Definition" : 'It refers to the process of automating operational efforts required for provisioning, deploying, scaling and managing application infrastructure.', "Reference": '36. https://cloud.google.com/discover/what-is-container-orchestration'},
  {'ID' : '37', "Term" : 'Load Balancing', "Definition" : ' It refers to the method of distributing the network traffic across the different network resources to ensure quick and reliable delivery of text, videos and other data to many users simultaneously', "Reference": '37. https://aws.amazon.com/what-is/load-balancing/#:~:text=Load%20balancing%20is%20the%20method,a%20fast%20and%20reliable%20manner.'},
  {'ID' : '38', "Term" : 'Security as Code', "Definition" : 'It is the process of integrating security checks and test into the code and infrastructure, it automates the process of testing done in each commit which saves time and cost.', "Reference": '38. https://about.gitlab.com/blog/2020/03/12/how-to-security-as-code/'},
  {'ID' : '39', "Term" : 'Continuous monitoring', "Definition" : 'It is a process of constantly monitoring IT infrastructure to enable rapid detection of compliance issues and security risks for quick response and action. It also allows monitoring of service quality.', "Reference": '39. https://www.sumologic.com/glossary/continuous-monitoring/'},
  {'ID' : '40', "Term" : 'Hybrid cloud', "Definition" : 'It refers to the use of multiple cloud platforms for deploying and running applications using different services from different platforms including computing and storage from public and private clouds.', "Reference": '40. https://cloud.google.com/learn/what-is-hybrid-cloud'},
  {'ID' : '41', 'Term' : 'Build agent', 'Definition' : ' It is a tool in cloud computing which can be installed locally or remotely and can manage cloud resources and software builds by sending and receiving messages.', 'Reference' : '41. https://medium.com/@DZoneInc/48-devops-terms-you-should-know-a-devops-glossary-37e60fd23752'},
  {'ID' : '42', 'Term' : 'Lead Time', 'Definition' : 'It refers to the time taken between completion of a software and the time it took for the software to be deployed to production environment.', 'Reference' : '42. https://www.software.com/devops-guides/lead-time#:~:text=Lead%20time%20in%20DevOps%20measures,delivering%20changes%20to%20the%20codebase.'},
  {'ID' : '43', 'Term' : 'Artifact repository', 'Definition' : 'It acts as a central repository for builds and offers an API to automatically deploy projects builds to the environments in the pipelines. It can remove artifacts automatically to free up space once a build is deployed.', 'Reference' : '43. https://www.jetbrains.com/teamcity/ci-cd-guide/concepts/artifact-repository/#:~:text=An%20artifact%20repository%20provides%20a,artifacts%20to%20free%20up%20space.'},
  {'ID' : '44', 'Term' : 'Branching', 'Definition' : 'It is a tool in version control systems using which developers can create separate code branches for development, after the work is finished and tested it is pushed to the trunk of the code.', 'Reference' : '44. https://www.heptabit.at/blog/devops/devops-branching-strategy-what-is-it-how-it-works#:~:text=Branching%20is%20the%20process%20of,be%20complicated%20and%20get%20messy.'},
  {'ID' : '45', 'Term' : 'Automated Release Management', 'Definition' : 'these refer to the set of tools which offer complete monitoring solution of the software in its lifecycle including application development process, quality assurance and production.', 'Reference' : '45. https://www.bmc.com/blogs/devops-release-management/#:~:text=Automated%20release%20management%20tools%20provide,and%20the%20reasons%20behind%20them.'},
  {'ID' : '46', 'Term' : 'Rollback', 'Definition' : 'It is the process of reverting back the application from a faulty state to a state which is a known good state until the latest version of the software is fixed.', 'Reference' : '46. https://learn.microsoft.com/en-us/azure/well-architected/devops/release-engineering-rollback'},
  {'ID' : '47', 'Term' : 'Service Mesh', 'Definition' : 'It is a specialised layer in the infrastructure which is built-in the application and manages service-to-service communication. It provides functionality such as load balancing and data encryption.', 'Reference' : '47. https://www.dynatrace.com/news/blog/what-is-a-service-mesh/#:~:text=A%20service%20mesh%20is%20a,data%2C%20and%20discovers%20other%20services.'},
  {'ID' : '48', 'Term' : 'Fault tolerance', 'Definition' : 'It refers to the ability of a system to keep functioning even in the events of failures in the hardware or the software which improves the reliability of the system.', 'Reference' : '48. https://www.educative.io/answers/what-is-fault-tolerance-in-cloud-computing'},
  {'ID' : '49', 'Term' : 'Production Environment', 'Definition' : 'It is the environment where the latest version of the software is deployed for the end-users. The final stage of production where end-users can interact with the system.', 'Reference' : '49. https://www.pagerduty.com/resources/learn/what-is-production-environment/#:~:text=Simply%20put%2C%20a%20production%20environment,interact%20with%20the%20new%20product.'},
  {'ID' : '50', 'Term' : 'Build artifacts', 'Definition' : 'These are the files that are created during the build process. Files such as packages, logs and test reports are artefacts created during the build process.', 'Reference' : '50. https://www.jetbrains.com/teamcity/ci-cd-guide/concepts/artifact-repository/#:~:text=An%20artifact%20repository%20provides%20a,artifacts%20to%20free%20up%20space.'},
];

/* GET home page. */
router.get('/', function(req, res, next) {
  res.render('index', { title: 'DevOps Glossary', Glossary: glossaryList });
});

module.exports = router;
